name: falando_speech_recognition
description: A flutter plugin to use the speech recognition on Falando App 
version: 0.0.1
author: Willian Mattos <willian_matt@hotmail.com>
homepage: https://github.com/zwillianmattos/speech-recognition

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0